export const ALL_RECIPES = 'ALL_RECIPES';
export const ALL_RECIPES_SUCCESS = 'ALL_RECIPES_SUCCESS';
export const ALL_RECIPES_FAILED = 'ALL_RECIPES_FAILED';

export const DELETE_RECIPE = 'DELETE_RECIPE';
export const DELETE_RECIPE_SUCCESS = 'DELETE_RECIPE_SUCCESS';
export const DELETE_RECIPE_FAILED = 'DELETE_RECIPE_FAILED';

export const CREATE_RECIPE = 'CREATE_RECIPE';
export const CREATE_RECIPE_SUCCESS = 'CREATE_RECIPE_SUCCESS';
export const CREATE_RECIPE_FAILED = 'CREATE_RECIPE_FAILED';

export const UPDATE_RECIPE = 'UPDATE_RECIPE';
export const UPDATE_RECIPE_SUCCESS = 'UPDATE_RECIPE_SUCCESS';
export const UPDATE_RECIPE_FAILED = 'UPDATE_RECIPE_FAILED';

export const GET_RECIPE_BY_ID = 'GET_RECIPE_BY_ID';
export const GET_RECIPE_BY_ID_SUCCESS = 'GET_RECIPE_BY_ID_SUCCESS';
export const GET_RECIPE_BY_ID_FAILED = 'GET_RECIPE_BY_ID_FAILED';

export const SORT_BY_STARS_DESC = 'SORT_BY_STARS_DESC';


